---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "common"
  namespace: "ztp-common"
spec:
  remediationAction: inform
  bindingRules:
    # These policies will correspond to all clusters with this label:
    common: "true"
  sourceFiles:
    # Create operators policies that will be installed in all clusters
    - fileName: SriovSubscription.yaml
      policyName: "subscriptions-policy"
      spec:
        installPlanApproval: Automatic
    - fileName: SriovSubscriptionNS.yaml
      policyName: "subscriptions-policy"
    - fileName: SriovSubscriptionOperGroup.yaml
      policyName: "subscriptions-policy"
    - fileName: SriovOperatorStatus.yaml
      policyName: "subscriptions-policy"
    - fileName: PtpSubscription.yaml
      policyName: "subscriptions-policy"
      spec:
        installPlanApproval: Automatic
    - fileName: PtpSubscriptionNS.yaml
      policyName: "subscriptions-policy"
    - fileName: PtpSubscriptionOperGroup.yaml
      policyName: "subscriptions-policy"
    - fileName: PtpOperatorStatus.yaml
      policyName: "subscriptions-policy"
    - fileName: ReduceMonitoringFootprint.yaml
      policyName: "config-policy"
    #
    # These CRs are in support of installation from a disconnected registry
    #
    - fileName: OperatorHub.yaml
      policyName: "config-policy"
    - fileName: DefaultCatsrc.yaml
      policyName: "config-policy"
      # The Subscriptions all point to redhat-operators. The OperatorHub CR
      # disables the defaults and this CR replaces redhat-operators with a
      # CatalogSource pointing to the disconnected registry. Including both of
      # these in the same policy orders their application to the cluster.
      metadata:
        name: redhat-operators
      spec:
        displayName: disconnected-redhat-operators
        image: test03.gpskr.local:5000/disconnected-redhat-operators/redhat/redhat-operator-index:v4.12
    - fileName: DisconnectedICSP.yaml
      policyName: "config-policy"
      spec:
        repositoryDigestMirrors:
        - mirrors:
          - test03.gpskr.local:5000/disconnected-redhat-operators/openshift4
          source: registry.redhat.io/openshift4
